@echo off
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=49152
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=464
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=123
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=593
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=53
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=8080
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=9300
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=9200
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP  localport=389
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=135
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=1024
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=49152
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=8443
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=1489
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=8014
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=443
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=49157
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=139
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=138
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=88
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=80
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=1688
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=636
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=3389
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=636
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=10050
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=389
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=1024
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=49157
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=137
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=65535
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=53
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=464
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=445
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=135
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=9090
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=137
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=5555
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=65535
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=8530
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=88
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=22
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=TCP localport=2967
netsh advfirewall firewall add rule name="FTI" dir=in action=allow protocol=UDP localport=139
done.